name: cd

on: # masterブランチに対してプルリクエストがマージされたことをトリガにして実行
  push:
    branches:
      - master

jobs:
  cd:
    name: cd
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Container registry に認証する # docker/login-actionも使える
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Dockerビルドを実行する # docker/build-push-actionも使える
        run: docker build -t ghcr.io/${{ github.repository }}:latest .
      - name: Docker イメージをプッシュする
        run: docker push ghcr.io/${{ github.repository }}:latest
